data_path: "F:\\Hyperspecial\\pear_processed\\hyperspecial_life_long_dataset_unoverlap"
run_times: 3
batch_size: 4
learn_rate: 0.0001
basic_task_index: 0
epoch_num: 200
patience: 10
pretrained_model_path: "log\\segment_model_pretrain.pth"
basic_model_save_path: "log\\basic_segment_model.pt"