data_path: "F:\\Hyperspecial\\pear_processed\\life_long_dataset"
run_times: 5
batch_size: 4
learn_rate: 0.0001
basic_task_index: 0
epoch_num: 200
patience: 10
pretrained_model_path: "log\\segment_model_pretrain.pth"
basic_model_save_path: ""